image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
    name: Webserver
  - port: 0-65535
    onOpen: ignore
tasks:
  - name: Webserver
    init: |
      fvm install -s
      fvm flutter config --no-analytics
      fvm dart --disable-analytics
      fvm flutter pub get
      curl https://get.volta.sh | bash -s -- --skip-setup
      volta install node
      npm i -g prettier
      npm ci
    command: fvm flutter run -d web-server --web-port=8080

vscode:
  extensions:
    - Dart-Code.flutter
    - EditorConfig.EditorConfig
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - GitHub.vscode-pull-request-github
    - eamodio.gitlens

github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addBadge: true
    addCheck: prevent-merge-on-error
