on: push
name: Cloudflare Pages
permissions:
  contents: read
  deployments: write
jobs:
  cloudflare-pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: volta-cli/action@v4.0.0
      - run: |
          npm ci
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap leoafarias/fvm
          brew install fvm
          fvm install
          fvm flutter build web --web-renderer=canvaskit
      - uses: cloudflare/pages-action@v1.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 9839aabb4253ed85d80549a8f99ee832
          projectName: streamflix
          directory: build/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
