on:
  push:
    branches:
      - main
name: Fix and format code
concurrency:
  group: fix-and-format-code
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  fix-and-format-code:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3.7.0
        with:
          node-version-file: package.json
          cache: npm
      - run: |
          npm install -g npm@$(jq -r .volta.npm package.json)
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew analytics off
          brew tap leoafarias/fvm
          brew install fvm
          fvm install -s
          fvm flutter pub get --suppress-analytics
          fvm dart --disable-analytics
          fvm dart fix --apply
          fvm dart format --fix lib
          npm ci
          npx prettier --write .
          git config --global user.name "GitHub Actions"
          git config --global user.email actions@noreply.github.com
          git commit -am "Fix and format code" || true
          git push
