on:
  pull_request:
    branches:
      - main
name: Fix and format code
permissions:
  contents: write
jobs:
  fix-and-format-code:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          ref: ${{ github.head_ref }}
      - uses: volta-cli/action@v4.0.0
      - run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap leoafarias/fvm
          brew install fvm
          fvm install
          fvm flutter pub get
          fvm dart fix --apply
          fvm dart format --fix lib
          npm ci
          npx prettier --write .
          git config --global user.name "GitHub Actions"
          git config --global user.email actions@noreply.github.com
          git commit -am "Fix and format code" || true
          git push
